# Generated by Django 3.2.9 on 2021-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='users_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
