# Generated by Django 3.2.9 on 2021-11-26 15:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='image'),
        ),
    ]
