# Generated by Django 3.2.9 on 2021-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extract',
            field=models.TextField(blank=True),
        ),
    ]
