# Generated by Django 3.2.9 on 2021-11-11 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='news_downvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
