# Generated by Django 3.2.9 on 2021-11-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_extract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='extract',
            field=models.TextField(max_length=100),
        ),
    ]
