# Generated by Django 3.2.9 on 2021-11-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211112_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_name',
            new_name='category',
        ),
    ]
