# Generated by Django 3.2.9 on 2021-11-11 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='news_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
