# Generated by Django 3.2.9 on 2021-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_category_name_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approve_category',
            field=models.BooleanField(default=False),
        ),
    ]
