# Generated by Django 3.2.9 on 2021-11-18 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_article_extract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='article',
            name='upvote',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created_upvote', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_vote', to='news.article')),
                ('upvote', models.ManyToManyField(blank=True, related_name='news_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
