# Generated by Django 3.2.9 on 2021-11-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_approve_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
