# Generated by Django 3.2.9 on 2021-11-18 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20211118_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='news_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='news_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
