# Generated by Django 3.2.9 on 2021-11-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20211108_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
