# Generated by Django 3.2.9 on 2021-11-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_time',
        ),
    ]
