# Generated by Django 3.2.9 on 2021-11-08 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20211108_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
