# Generated by Django 3.2.9 on 2021-11-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_article_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='featured_image',
        ),
    ]
