# Generated by Django 3.2.9 on 2021-11-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
