# Generated by Django 3.2.9 on 2021-11-09 13:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='image'),
        ),
    ]
