# Generated by Django 3.2.9 on 2021-11-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20211109_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='image',
        ),
    ]
